---
jobs:
  - job: LinuxTest
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - script: curl -sSL https://get.haskellstack.org/ | sh
        displayName: Install stack

      - script: stack test
        displayName: Run tests

  - job: MacOSTest
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - script: curl -sSL https://get.haskellstack.org/ | sh
        displayName: Install stack

      - script: stack test
        displayName: Run tests

  - job: WindowsTest
    pool:
      vmImage: 'VS2017-Win2016'
    steps:
      - script: choco install haskell-stack
        displayName: Install stack

      - script: stack test
        displayName: Run tests
