---
name: fake-json
version: 0.1.0.0
github: "mfussenegger/fake-json"
license: MIT
author: "Mathias Fußenegger"
maintainer: "github@zignar.net"
copyright: "2018 Mathias Fußenegger"

extra-source-files:
  - README.md
  - ChangeLog.md

description: |
  Please see the README on GitHub at <https://github.com/mfussenegger/fake-json#readme>

ghc-options:
  - -Wall
  - -fno-warn-unused-do-bind
  - -fwarn-tabs
  - -fwarn-incomplete-uni-patterns
  - -fwarn-incomplete-record-updates
  - -Wcompat
  - -Widentities
  - -Wredundant-constraints
  - -Wpartial-fields
  - -fhide-source-paths
  - -freverse-errors

dependencies:
  - base >= 4.7 && < 5
  - text
  - aeson
  - bytestring
  - scientific
  - uuid
  - parsec
  - random
  - scientific
  - mtl
  - vector
  - unordered-containers
  - containers
  - regex-tdfa
  - optparse-applicative
  - time
  - ulid

library:
  source-dirs: src

executables:
  fake-json:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -rtsopts
    dependencies:
      - fake-json
    when:
      - condition: flag(static)
        ld-options:
          - -static
        ghc-options:
          - fPIC

tests:
  fake-json-test:
    main: spec.hs
    source-dirs: tests
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - fake-json
  fake-json-doctest:
    main: doctests.hs
    source-dirs: tests
    dependencies:
      - fake-json
      - Glob
      - doctest

flags:
  static:
    description: Pass -static to ghc when linking the binary.
    manual: true
    default: false
