---
name: fake-json
version: 0.1.0.0
github: "mfussenegger/fake-json"
license: MIT
author: "Mathias Fußenegger"
maintainer: "github@zignar.net"
copyright: "2018 Mathias Fußenegger"

extra-source-files:
  - README.md
  - ChangeLog.md

description: |
  Please see the README on GitHub at <https://github.com/mfussenegger/fake-json#readme>

ghc-options:
  - -Wall
  - -fno-warn-unused-do-bind

dependencies:
  - base >= 4.7 && < 5
  - text
  - aeson
  - bytestring
  - scientific
  - uuid
  - parsec
  - random
  - scientific
  - transformers

library:
  source-dirs: src

executables:
  fake-json:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -rtsopts
    dependencies:
      - fake-json

tests:
  fake-json-test:
    main: spec.hs
    source-dirs: tests
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - fake-json
  fake-json-doctest:
    main: doctests.hs
    source-dirs: tests
    dependencies:
      - fake-json
      - doctest
