---
name: CI

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Cache dependencies
        uses: freckle/stack-cache-action@main

      - name: Build and test Haskell code
        run: |
          stack --no-terminal build --pedantic --flag mkjson:-static --test
